package com.yash.store.model.enums;

public enum State {
    ANDHRA_PRADESH, ARUNACHAL_PRADESH, ASSAM, BIHAR,
    CHHATTISGARH, GOA, GUJARAT, HARYANA, HIMACHAL_PRADESH,
    JHARKHAND, KARNATAKA, KERALA, MADHYA_PRADESH,
    MAHARASHTRA, MANIPUR, MEGHALAYA, MIZORAM, NAGALAND,
    ODISHA, PUNJAB, RAJASTHAN, SIKKIM, TAMIL_NADU,
    TELANGANA, TRIPURA, UTTAR_PRADESH, UTTARAKHAND,
    WEST_BENGAL
}
